CREATE DATABASE IF NOT EXISTS `RESOURCEHUB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `RESOURCEHUB`;

CREATE TABLE USER(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL,
    STUDENT_ID VARCHAR(50) NOT NULL,
    USER_EMAIL VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(50) NOT NULL,
    USER_TYPE VARCHAR(50) NOT NULL,
    APPROVED BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (USER_ID)
);


CREATE TABLE RESOURCE(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RESOURCE_NAME VARCHAR(50) NOT NULL,
    RESOURCE_TYPE  VARCHAR(50) NOT NULL,
    OPTIONAL_DETAILS VARCHAR(100) NOT NULL,
    BUILDING_NAME VARCHAR(50) NOT NULL,
    SEATING INT NOT NULL,
    IMAGE VARCHAR(50) NOT NULL
);

CREATE TABLE EVENTS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EVENT_NAME VARCHAR(50) NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    CONDUCT_BY VARCHAR(50) NOT NULL,
    OPTIONAL_DETAILS VARCHAR(100) NOT NULL,
    RECURRING BOOLEAN NOT NULL,
    TEMP BOOLEAN DEFAULT FALSE,
);

CREATE TABLE TIME_SLOT(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    START_TIME INT NOT NULL,
    END_TIME INT NOT NULL,
    DAY VARCHAR(50) NOT NULL
);

CREATE TABLE OCCUPIED(
    RESOURCE_ID INT NOT NULL,
    EVENT_ID INT NOT NULL,
    TIME_SLOT_ID INT NOT NULL,
    OCCUPIED_DATE DATE DEFAULT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE(ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID),
    FOREIGN KEY (TIME_SLOT_ID) REFERENCES TIME_SLOT(ID),
    PRIMARY KEY (RESOURCE_ID, EVENT_ID, TIME_SLOT_ID)
);



ALTER TABLE OCCUPIED ADD COLUMN ACTIVE BOOLEAN NOT NULL DEFAULT TRUE;





CREATE TABLE REQUEST(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    RESOURCE_ID INT NOT NULL,
    EVENT_ID INT NOT NULL,
    TIME_SLOT_ID INT NOT NULL,
    REQUEST_DATE DATE DEFAULT NULL,
    APPROVED BOOLEAN NOT NULL DEFAULT FALSE,
    PRIORITY INT NOT NULL DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE(ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID),
    FOREIGN KEY (TIME_SLOT_ID) REFERENCES TIME_SLOT(ID)
);